### ISSUE TITLE
Potrebna mi je Vasa pomoc.

### ISSUE THREAD

**Issue by zumbuuul** [cacafaca/EsDnevnik#12]
Pozdrav Nemanja!

Probao sam da Vas kontaktiram na LinkedIn-u ali imao sam ili neki problem do samog LinkedIna ili Vam je onemugceno connectovanje sa ostalima, pa moram ovako da Vam se obratim.

Naime, i sam sam ucenik i trenutno razvijam aplikaciju za biblioteku moje skole, nazalost nisam bio uspesan u nalazenju public esDnevnik APIa, ali sam nalutao na ovaj repo.

Bili bi mi od velike pomoci ako bi mogli da mi ostavite neki link/guide kako ste Vi uspeli da se docepate APIa.

Srdacan pozdrav i neizmerno Vam hvala!

**Comment by cacafaca** [comment]
Срећан Божић Лазаре!

Не постоји документација за АПИ. Морао сам са програмерским алатом (Ф12 у
популарним прегледача) да сам откривам.

Поздрав,
Немања Симовић

суб, 7. јан 2023. 16:09 Lazar ***@***.***> је написао/ла:

**Comment by zumbuuul** [comment]
Hristos vaskrse!

Hvala Vam puno, problem resen! 🥂
